<?php

namespace App\Controller;

use App\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/home", name="home");
     * @Route("/");
     * @Route("/views");
     *
     *
     */
    public function index()
    {
        return $this->render('views/index.html.twig', [
            'controller_name' => 'Home',
        ]);
    }

    public function show(EntityManagerInterface $em )
    {
        $repository = $em->getRepository(User::class);
        $user = $repository->find(1);
        return parent::getUser(); // TODO: Change the autogenerated stub
    }

}
